---
service:
    dataset: 'newfile3.txt'
    filepath: "/home/nuxion/Proyects/femicidio/datasets/"
    scheme: 'scheme.yml'
logger:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: 'DEBUG'
    path: 'justicia.log'
elastic:
    hostname: 'localhost'
    port: 9200
    index: 't_f1'
    user: ''
    pass: ''
